stages:
- lint
- build
- build-review
- review
- release

# CHANGE ME!
variables:
  REPO: "templates/latex-report"
  AUTHPASSWORD: "example" # change to "" (empty string) to disable authentication
  # username is always "review" (without quotes)

include:
- 'https://git.dbogatov.org/templates/ci-snippets/raw/master/latex-report/chktex.yml'
- 'https://git.dbogatov.org/templates/ci-snippets/raw/master/latex-report/cspell.yml'
- 'https://git.dbogatov.org/templates/ci-snippets/raw/master/latex-report/build.yml'
- 'https://git.dbogatov.org/templates/ci-snippets/raw/master/latex-report/artifacts.yml'
- 'https://git.dbogatov.org/templates/ci-snippets/raw/master/latex-review-apps/build-review.yml'
- 'https://git.dbogatov.org/templates/ci-snippets/raw/master/latex-review-apps/review.yml'
- 'https://git.dbogatov.org/templates/ci-snippets/raw/master/latex-review-apps/stop-review.yml'
