stages:
- lint
- build
- release

include:
# - 'https://git.dbogatov.org/templates/ci-snippets/raw/master/latex-report/chktex.yml'
# - 'https://git.dbogatov.org/templates/ci-snippets/raw/master/latex-report/cspell.yml'
- 'https://git.dbogatov.org/templates/ci-snippets/raw/master/latex-report/build.yml'
# - 'https://git.dbogatov.org/templates/ci-snippets/raw/master/latex-report/artifacts.yml'

dockerify:
  stage: release
  dependencies:
  - build
  script:
  - |
    docker build \
      --build-arg PROJECTNAME=$CI_PROJECT_NAME \
      --build-arg PROJECTURL=$CI_PROJECT_URL \
      --build-arg COMMIT=$CI_COMMIT_SHA \
      -t registry.dbogatov.org/templates/latex-report/review/$CI_COMMIT_REF_NAME .
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.dbogatov.org
  - docker push registry.dbogatov.org/templates/latex-report/review/$CI_COMMIT_REF_NAME
  tags:
  - shell
