stages:
- lint
- build
- build-review
- review
- release

# CHANGE ME!
variables:
  AUTHPASSWORD: "example" # change to "" (empty string) to disable authentication
  # username is always "review" (without quotes)
  CI_REF: &ref 1240e7c6ccce1d40e0127353e40663a894dbe0d2

include:
  # VARIABLES
  - project: 'templates/ci-snippets'
    file: 'latex-report/variables.yml'
    ref: *ref

  # BEFORE SCRIPT
  - project: 'templates/ci-snippets'
    file: 'variables.yml'
    ref: *ref

  # LINT
  - project: 'templates/ci-snippets'
    file: 'latex/chktex.yml'
    ref: *ref

  - project: 'templates/ci-snippets'
    file: 'latex/cspell.yml'
    ref: *ref

  - project: 'templates/ci-snippets'
    file: 'latex-report/metrics.yml'
    ref: *ref

  # BUILD
  - project: 'templates/ci-snippets'
    file: 'latex/build.yml'
    ref: *ref
  
  # BUILD REVIEW
  - project: 'templates/ci-snippets'
    file: 'latex-review-apps/build-review.yml'
    ref: *ref
  
  # REVIEW
  - project: 'templates/ci-snippets'
    file: 'latex-review-apps/review.yml'
    ref: *ref
    
  - project: 'templates/ci-snippets'
    file: 'latex-review-apps/stop-review.yml'
    ref: *ref
  
  # RELEASE
  - project: 'templates/ci-snippets'
    file: 'latex/artifacts.yml'
    ref: *ref

  - project: 'templates/ci-snippets'
    file: 'latex/pages.yml'
    ref: *ref

# ADJUSTMENTS

build-review:
  except: []

review:
  except: []

stop_review:
  except: []
