stages:
- lint
- build
- build-review
- review
- release

# CHANGE ME!
variables:
  REPO: "templates/latex-report"
  AUTHPASSWORD: "example" # change to "" (empty string) to disable authentication
  # username is always "review" (without quotes)

include:
  # LINT
  - project: 'templates/ci-snippets'
    file: 'latex-assignments/chktex.yml'
  
  - project: 'templates/ci-snippets'
    file: 'latex-assignments/cspell.yml'
    
  - project: 'templates/ci-snippets'
    file: 'latex-assignments/metrics.yml'
    
  # BUILD
  - project: 'templates/ci-snippets'
    file: 'latex-assignments/build.yml'
  
  # BUILD REVIEW
  - project: 'templates/ci-snippets'
    file: 'latex-review-apps/build-review.yml'
  
  # REVIEW
  - project: 'templates/ci-snippets'
    file: 'latex-review-apps/review.yml'
    
  - project: 'templates/ci-snippets'
    file: 'latex-review-apps/stop-review.yml'
  
  # RELEASE
  - project: 'templates/ci-snippets'
    file: 'latex-assignments/artifacts.yml'
