stages:
- lint
- build
- build-review
- review
- release

# CHANGE ME!
variables:
  AUTHPASSWORD: "example" # change to "" (empty string) to disable authentication
  # username is always "review" (without quotes)

include:
  # VARIABLES
  - project: 'templates/ci-snippets'
    file: 'latex-report/variables.yml'

  # BEFORE SCRIPT
  - project: 'templates/ci-snippets'
    file: 'variables.yml'

  # LINT
  - project: 'templates/ci-snippets'
    file: 'latex/chktex.yml'

  - project: 'templates/ci-snippets'
    file: 'latex/cspell.yml'

  - project: 'templates/ci-snippets'
    file: 'latex-report/metrics.yml'

  # BUILD
  - project: 'templates/ci-snippets'
    file: 'latex/build.yml'
  
  # BUILD REVIEW
  - project: 'templates/ci-snippets'
    file: 'latex-review-apps/build-review.yml'
  
  # REVIEW
  - project: 'templates/ci-snippets'
    file: 'latex-review-apps/review.yml'
    
  - project: 'templates/ci-snippets'
    file: 'latex-review-apps/stop-review.yml'
  
  # RELEASE
  - project: 'templates/ci-snippets'
    file: 'latex/artifacts.yml'

  - project: 'templates/ci-snippets'
    file: 'latex/pages.yml'

# ADJUSTMENTS

build-review:
  except: []

review:
  except: []

stop_review:
  except: []
